"""add user_id to applications

Revision ID: 007355fb8d5c
Revises: 007ad2c955bc
Create Date: 2026-08-30 11:28:16.236692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007355fb8d5c'
down_revision: Union[str, Sequence[str], None] = '007ad2c955bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'applications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'user_id')
    # ### end Alembic commands ###
