"""add location attribute

Revision ID: 3e6235b07f75
Revises: 9b9a91fabbd3
Create Date: 2026-08-26 07:36:33.700134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6235b07f75'
down_revision: Union[str, Sequence[str], None] = '9b9a91fabbd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('location', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'location')
    # ### end Alembic commands ###
